## 2. fancy 인덱싱

#### fancy 인덱싱은 범위가 아님 특싱 index의 집합의 값을 선택하여 추출하고 싶을 때 활용

In [27]:
import numpy as np

In [3]:
arr= np.array([10,23,3,7,4,43,67,90])

- 반드시 [추출하고 싶은 인덱스]를 꺽쇠 괄호에 묶어주기

In [4]:
arr[[1,3,5]]

array([23,  7, 43])

In [5]:
idx= [2,4,6,7]
arr[idx]

array([ 3,  4, 67, 90])

- 1차원 배열(벡터)의 fancy 인덱싱 연습
  - 아래 주어진 1차원 배열에서 (4,7,11,13,17,13)만 추출하시오  (fancy인덱싱활용)

In [8]:
a= np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
idx= [4,7,11,13,17,23]
a[idx]

array([ 4,  7, 11, 13, 17, 23])

### 2차원 array에서 fancy 인덱싱

In [15]:
arr2d= np. random.randint(1,30,size=(3,5))
arr2d

array([[18, 20, 22, 20, 27],
       [20, 23,  3, 17, 14],
       [10, 25,  9, 16, 15]])

In [20]:
arr2d[1:2,[1,2,4]]   #행: 슬라이싱, 열: 인덱싱

array([[23,  3, 14]])

In [21]:
arr2d[:,[0]]

array([[18],
       [20],
       [10]])

### 3. boolean 인덱싱

- 조건 필터링을 통해 boolean 값을 이용한 색인

- 조건을 주고, 조건에 만족하는 값만 가져오는 것이 핵심

In [22]:
arr= np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr2d = np. arange(1,13). reshape(3,4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
bool_mask[True, False, True]
arr[bool_mask]  # bool_mask 리스트 원소 개수랑 달라서 에러

NameError: name 'bool_mask' is not defined

In [30]:
bool_mask = [True, False,True, True, False,True,True,False,True]
arr[bool_mask]

array([1, 3, 4, 6, 7, 9])

### 3-1. 조건필터

- 조건 연산자를 활용하여 필터를 활용할 수 있음

In [31]:
arr2d = np.arange(1,13).reshape(3,4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
arr2d>3

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

- 필터를 활용하여 필터에 true 조건만 색인합니다.

- 조건을 꺽쇠괄호로 한번 묶어주기 (fancy 인덱싱과 유사)

In [34]:
arr2d[arr2d>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

- arr2d에서 5보다 작거나 같은 값만 추출하시오

In [36]:
arr2d[arr2d<=5]

array([1, 2, 3, 4, 5])

In [37]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- 3의 배수만 추출하기

In [38]:
arr2d[arr2d%3==0]

array([ 3,  6,  9, 12])

### 3-2 다중 조건 사용하기
- 파이썬 논리 연산자인 and, or, not 키워드 사용물가
- & : and
- |  : or

In [41]:
x= np. random.randint(1,100,size = 10)
x

array([42, 69, 84, 20, 84, 20, 98, 49, 97, 32])

In [42]:
x[x%2==0]

array([42, 84, 20, 84, 20, 98, 32])

In [43]:
x[x>60]

array([69, 84, 84, 98, 97])

In [45]:
x[(x>30)&(x<70)] #and x의 원소가 30보다 크고, 70보다 작은 x의 원소

array([42, 69, 49, 32])

In [47]:
x[(x>60)|(x%3==0)] #or x의 원소가 60보다 크거나, 홀수인 x의 원소

array([42, 69, 84, 20, 84, 20, 98, 49, 97, 32])

- 예제) 2019년 7월 서울 평균기온 데이터
   - 평균기온이 25도를 넘는 날 수
   - 평균기온이 25도를 넘는 날의 평균 기온은?

In [48]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [71]:
len(temp)

31

In [70]:
len(temp[temp>25.0])        #bool리스트의 길이 구하기로 값을 찾는다.

21

In [68]:
np.sum(temp>25.0)  #bool리스트의 true값 합계로 값을 찾는다.

21

In [69]:
np.mean(temp[temp>25.0])

26.857142857142858

## 정렬: sort

## 1차원 정렬

- 1차원 정렬은 매우간단

In [73]:
arr = np.array([1,10,5,8,2,4,3,6,8,7,9])
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [84]:
arr3 = np.sort(arr)

- 기본적으로 오름차순으로 정렬 수행

In [76]:
np.sort(arr)[::-1] #내림차순 정렬, 암기!!

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

- 내림차순 정렬은 옵션에 -1값을 주면 됩니다.
- 그러나 이 값들은 유지가 안됨.
- 값을 정렬된 상태로 저장하려면, 배열 자체에 sort를 해줄 수 있다.

In [78]:
arr2 = np.sort(arr)[::-1]

In [80]:
arr2

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [85]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [87]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

### 2. N차원 정렬

- shape와 axis가 중요

- axis 기준으로 정렬됨

In [91]:
arr2d = np.array([[5,6,7,8],[4,3,2,1],[10,9,12,11]])

In [92]:
arr2d.shape

(3, 4)

In [93]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

### 2-1. 열정렬 (왼쪽에서 오른쪽으로)

In [95]:
np.sort(arr2d,axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

### 2-1 행 정렬 (위에서 아래로)

In [96]:
np. sort(arr2d, axis =0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])