# 파이썬 라이브러리
##  numpy : 고성능 과학계산을 위한 데이터 분석 라이브러리

## pandas: 형과 열로 구성된 표 형식의 데이터를 지원하는 라이브러리

## matplotlip

### numpy의 주요 기능: 빠르고 효율적인 벡터 산술연산을 제공하는 다차원배열 제공 (ndarray 클래스)

### 모듈사용하기

In [3]:
import numpy as np

In [4]:
arr1 = np. array ([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [5]:
list1 = [1,2,3,4]
list1

[1, 2, 3, 4]

In [6]:
type(arr1)

numpy.ndarray

In [7]:
type(list1)

list

## 리스트 사용하여 넘파이 배열 생성

In [8]:
list1= [1,2,3,4,5]

In [10]:
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 5])

In [11]:
type(arr1)

numpy.ndarray

In [12]:
arr2= np.array([1,2,3,4])
arr2

array([1, 2, 3, 4])

## 2차원 배열 생성

In [16]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

## 배열 크기(차원) 확인하기

In [25]:
arr1.shape

(5,)

In [26]:
arr2.shape

(2, 3)

### array에서 data type
- array에서는 list와 다르게 1개의 단일 데이터 타입만 허용됨
- list에서의 datatype

In [27]:
mylist = [1,3,14,'스마트','1234'] #리스트에서는 데이터 혼합가능

In [28]:
mylist

[1, 3, 14, '스마트', '1234']

In [30]:
mylist[3]

'스마트'

### array에서의 데이터 타입

In [34]:
list1 = [1,2,3,3.14]
arr = np. array([1,2,3,3.14]) #혼재되었으니, array가 정수를 실수로 바꿈

In [35]:
list1

[1, 2, 3, 3.14]

In [37]:
arr

array([1.  , 2.  , 3.  , 3.14])

### int와 float타입 혼재되었으나, dtype을 지정한 경우

In [50]:
arr1 = np.array([1,2,3,3.14],dtype = int) #dtype: 자료형이 가지는 원소의 데이터 타입

In [51]:
arr1

array([1, 2, 3, 3])

### int와 str타입이 혼재된 경우

In [44]:
arr2 = np.array([1,3.14,'스마트','1234'])

In [45]:
arr2

array(['1', '3.14', '스마트', '1234'], dtype='<U32')

### int와 str 타입이 혼재되어 있고, int로 dtype을 지정한 경우

In [52]:
arr3 = np.array ([1,3.14,'1234'], dtype = int)

In [54]:
arr3

array([   1,    3, 1234])