### 1. 인덱싱과 슬라이싱 활용하기

In [2]:
import numpy as np

#### 인덱싱 
- 파이썬 **리스트와 동일한 개념** 으로 사용
- , 를 사용하여 각 차원의 인덱스에 접근가능

- 1차원 벡터 인덱싱

In [5]:
x= np. arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
type(x)

numpy.ndarray

In [8]:
x[3]

3

In [9]:
x[3] = 100

In [10]:
print(x)

[  0   1   2 100   4   5   6   7   8   9]


In [11]:
x= np.arange(10).reshape(2,5) #arange로 배열원소 생성과 동시에 reshape으로 배열 모양 재성형
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
x[:,1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [16]:
x[:,:1]

array([[0],
       [5]])

### 연습
- 주어진 배열에서 3,4,8,9 원소만 가져오기 
x= np.arange(10).reshape(2,5)

In [17]:
x= np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [19]:
x[:,3:]

array([[3, 4],
       [8, 9]])

In [22]:
x[1,1:4]

array([6, 7, 8])

#### 슬라이싱 할때, 인덱스 범위
- [시작 **이상**: 끝**미만**]

In [23]:
y= np. arange(15).reshape(3,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


- 1. (3,8,13) 원소 가져오기
- 2. (5,6,7,8,9) 원소 가져오기
- 3. (1,2,3,6,7,8) 원소 가져오기

In [40]:
print(y[:,3]) #인덱싱 : 차원축소
print(y[:,3:4]) #슬라이싱: 차원유지

[ 3  8 13]
[[ 3]
 [ 8]
 [13]]


In [30]:
y[1,:] #슬라이싱

array([5, 6, 7, 8, 9])

In [45]:
y[:2,1:4]

array([[1, 2, 3],
       [6, 7, 8]])

- 3차원 텐서 슬라이싱

In [47]:
x= np.arange(54).reshape(2,3,9)
print(x)

[[[ 0  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]
  [18 19 20 21 22 23 24 25 26]]

 [[27 28 29 30 31 32 33 34 35]
  [36 37 38 39 40 41 42 43 44]
  [45 46 47 48 49 50 51 52 53]]]


In [48]:
x[:1,:2,:]

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]])

In [53]:
x[:1,:2,6:]

array([[[ 6,  7,  8],
        [15, 16, 17]]])

- 1. 첫번 째 2차원 행렬을 슬라이싱

- 2. 그 다음 2차원 행렬의 두개를 슬라이싱

- 3. 슬라이싱 한 행렬의 행의 열 원소 다 가져오기

In [51]:
x[1:2,:2,6:] 

array([[[33, 34, 35],
        [42, 43, 44]]])

In [58]:
x[1:2,:,3:6] #인덱싱: 차원축소

array([[[30, 31, 32],
        [39, 40, 41],
        [48, 49, 50]]])