## 특정한 값으로 배열 생성하기
- 0으로 초기화

In [1]:
import numpy as np

In [3]:
arr_zeros = np. zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
arr_zeros1 = np.zeros((3,4), dtype = int)
arr_zeros1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

- 1로 초기화

In [8]:
arr_ones = np.ones((3,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
arr_ones1 = np.ones((3,4), dtype = int)
arr_ones1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

- 특정한 값으로 배열 생성하기: full

In [11]:
arr_full = np. full((5,4),7.2)
arr_full

array([[7.2, 7.2, 7.2, 7.2],
       [7.2, 7.2, 7.2, 7.2],
       [7.2, 7.2, 7.2, 7.2],
       [7.2, 7.2, 7.2, 7.2],
       [7.2, 7.2, 7.2, 7.2]])

#### 1~50까지 값을 갖는 1차원 리스트 생성

In [13]:
list1 =[]
for i in range(1,51): #range(초기값, 끝값+1, 간격)
     list1.append(i)
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [ ]:
arr = np. array(list1) #리스트를 이용하여 배열 생성

### 배열 생성하는 함수 : arrange

In [15]:
arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

##### 연습
- 1부터 50까지 짝수만 원소로 갖는 넘파이 배열 생성!!!

In [18]:
arr = np.arange(2,51,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

- 0을 원소로 갖는 4*4 배열 생성
- 1을 원소로 갖는 10*10 배열 생성
- 본인이 좋아하는 숫자를 원소로 갖는 7*4 배열 생성

In [32]:
arr1 = np.zeros((4,4),dtype = int)
arr2 = np.ones((10,10), dtype = int)
arr3= np.full((7,4),7, dtype = int)

In [27]:
arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
arr2

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [34]:
arr3

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

- 1부터 100까지 원소 중 3의 배수를 원소로 갖는 넘파이 배열 생성

In [36]:
arr1= np.arange(3,101,3)
arr1

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

- 만들어진 3의 배수를 원소로 갖는 넘파이 배열의 크기를 구하고 reshape함수를 이용하여 2차원 배열을 생성하시오.
- 생성된 2차원 배열의 크기를 구하시오.

In [52]:
arr1.size

33

In [53]:
arr2= arr1.reshape(11,3)

In [54]:
arr2.shape

(11, 3)

### 랜덤 값으로 배열 생성하기

In [56]:
import random

- rand : (0~1사이 값을 랜덤하게 생성)

In [58]:
arr = np.random.rand(2,4)
arr

array([[0.49271416, 0.32014884, 0.97524384, 0.92484545],
       [0.10362582, 0.55272148, 0.38313209, 0.72543418]])

- rand int (시작값, 끝값 , size = 배열크기)  
- 배열 크기는 튜플형태

In [63]:
arr = np.random.randint(1,45, size = (1,6))
arr

array([[29, 37, 25, 17, 17, 15]])

### 타입 변경하기: astype ('변경하려는 데이터 타입')

In [64]:
arr1= np. array([1,2,3,4,5,6,7,8])
arr2 = arr1.astype('float64')
arr2

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [65]:
print(arr1.dtype)
print(arr2.dtype)

int32
float64


- 예제

### 1. 0~1 사이의 값을 랜덤하게 가지는 6*4 배열을 생성하시오.

### 2. 1~100 사이의 값을 랜덤하게 가니는 5*5 배열을 생성하시오.

### 3. astype을 사용하여 2번의 배열을 실수형태의 원소로 가지는 배열로 바꾸시오.

In [67]:
arr7= np.random.rand(6,4)
arr7

array([[0.35885354, 0.20609084, 0.44212777, 0.46051405],
       [0.11350375, 0.82153176, 0.65278814, 0.0366348 ],
       [0.12709659, 0.01371587, 0.63410301, 0.72250092],
       [0.58686049, 0.35507082, 0.30567946, 0.65742445],
       [0.03464147, 0.86855408, 0.77442447, 0.03346925],
       [0.28939649, 0.57958388, 0.62490562, 0.24149723]])

In [70]:
arr8 = np.random.randint(1,100,size = (5,5))
arr8

array([[18,  4, 13, 69, 37],
       [63, 14,  4, 89, 94],
       [11, 41, 42, 11,  8],
       [76, 68, 97, 22, 90],
       [18, 30, 72, 38, 94]])

In [72]:
arr9 = arr8.astype('float64')
arr9

array([[18.,  4., 13., 69., 37.],
       [63., 14.,  4., 89., 94.],
       [11., 41., 42., 11.,  8.],
       [76., 68., 97., 22., 90.],
       [18., 30., 72., 38., 94.]])

In [74]:
arr9.ndim

2

In [75]:
arr9.shape

(5, 5)

In [ ]:
import