In [2]:
import numpy as np

### 배열 전체 요소 개수 확인하기

In [4]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
print(arr1.size)

5


In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(arr2.size)

6


In [45]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [46]:
arr3.shape

(2, 2, 3)

## 배열의 타입 확인

In [13]:
print(arr1.dtype)

int32


## 배열의 차원확인

In [17]:
print(arr1.ndim)

1


In [18]:
print(arr2.ndim)

2


In [19]:
print(arr3.ndim)

3


### 연습문제
- numpy를 이용해 원소개수가 8개인 3차원 배열을 만들고 배열의 크기, 차원, 전체 요소 개수를 확인해보자

In [21]:
arr3 = np.array([[[1, 2], [3,4]], [[5,6], [7,8]]])

In [22]:
arr3 #arr4 = arr3.reshape(2,2,2)해서 reshape함수를 써도 됨

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
print('배열의 크기:' ,arr3.shape)
print ('배열의 차원:',arr3.ndim)
print ('배열의 개수:' ,arr3.size)

배열의 크기: (2, 2, 2)
배열의 차원: 3
배열의 개수: 8


### 연습문제 2

### 1번문제

In [37]:
list1= [1,2,3,2,5,'345']
arr4 = np.array([list1], dtype = int)

In [38]:
arr4.dtype

dtype('int32')

In [39]:
list2 = [1,2,3,2,5,'345']
arr5 =  np.array([list2], dtype = float)

In [40]:
arr5.dtype

dtype('float64')

### 2번문제

In [41]:
list3 = [1,2,3,2,5,'인재','파이썬', '3,4,5']
arr6 = np.array([list3],dtype = str)

In [42]:
arr6.dtype

dtype('<U5')

### 3번문제

In [48]:
arr7 = np.array([1,2,3,4,5,6,7,8,9])

In [66]:
arr1 = arr7.reshape(3,3)

In [68]:
arr1.ndim

2