In [3]:
import numpy as np
import random

## numpy 기본 함수

#### 연산 함수
- add, substract, multiply, divide

In [7]:
x= np.arange(15).reshape(3,5)
y = np.random.randint(100, size= (3,5))
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[60 47 69 13 25]
 [27 89 87 13 48]
 [66 37  2 64 26]]


In [8]:
np.add(x,y)

array([[60, 48, 71, 16, 29],
       [32, 95, 94, 21, 57],
       [76, 48, 14, 77, 40]])

In [11]:
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))

[[-60 -46 -67 -10 -21]
 [-22 -83 -80  -5 -39]
 [-56 -26  10 -51 -12]]
[[  0  47 138  39 100]
 [135 534 609 104 432]
 [660 407  24 832 364]]
[[0.         0.0212766  0.02898551 0.23076923 0.16      ]
 [0.18518519 0.06741573 0.08045977 0.61538462 0.1875    ]
 [0.15151515 0.2972973  6.         0.203125   0.53846154]]


### 통계함수
- 평균, 분산, 중앙값, 최대값, 최소값 등등 통계관련 함수가 내장

In [13]:
print(y)

[[60 47 69 13 25]
 [27 89 87 13 48]
 [66 37  2 64 26]]


In [14]:
np.mean(y) #평균: numpy에서 제공하는 함수

44.86666666666667

In [16]:
y.mean() #파이썬 내장함수

44.86666666666667

In [17]:
np.max(y) #최대값

89

In [18]:
np.var(y) #분산

690.7822222222222

In [19]:
np.median(y) #중앙값

47.0

In [20]:
np.min(y)  #최소값

2

In [21]:
np.std(y) #표준편차

26.28273620120672

#### 집계함수
- 합계 (sum), 누적합계 (cumsum)등등 계산 가능

In [23]:
y

array([[60, 47, 69, 13, 25],
       [27, 89, 87, 13, 48],
       [66, 37,  2, 64, 26]])

In [26]:
np.sum(y,axis = None)

673

In [27]:
np. cumsum(y)  #누적합계: 누적값 그래프 그릴때 유용

array([ 60, 107, 176, 189, 214, 241, 330, 417, 430, 478, 544, 581, 583,
       647, 673], dtype=int32)