In [13]:
import numpy as np

In [15]:
data= np.loadtxt('height_weight.txt', delimiter =",")
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [17]:
data.shape

(2, 10)

In [22]:
#데이터를 키와 몸무게로 나누기
height_cm = data[0]
weight_kg = data[1]
#키 cm를 m로 환산
height_m = height_cm/100
#bmi 지수 구하기
bmi   = weight_kg/(height_cm*height_cm)
print(bmi)

[0.00213715 0.00270702 0.00258612 0.00242065 0.00160354 0.00201449
 0.00231439 0.00216972 0.00236203 0.00255922]


### boolean 색인

In [23]:
name = np. array(['철수', '영희', '순이', '바둑이'])
name

array(['철수', '영희', '순이', '바둑이'], dtype='<U3')

In [25]:
name_score = np. array([[70,70],[80,80],[90,90],[85,85]])
name_score

array([[70, 70],
       [80, 80],
       [90, 90],
       [85, 85]])

In [26]:
name_score [name == '바둑이']

array([[85, 85]])

In [29]:
data = np.loadtxt('ratings.txt',delimiter= '::',dtype = 'int')

In [30]:
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [32]:
print (data.shape)   #데이터 크기(모양새)
print (data.ndim)    #데이터 차원
print(data.size)     #데이터 원소개수


(1000209, 4)
2
4000836


### 1번 유저의 전체 정보 출력

In [34]:
#id 정보만 가져오기
user_id= data[:,0]
print(user_id)

[   1    1    1 ... 6040 6040 6040]


In [35]:
user_id_bfilter = user_id==1

In [37]:
print(user_id_bfilter)

[ True  True  True ... False False False]


In [38]:
#boolean 인덱싱
data[user_id_bfilter]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

In [41]:
data[data[:,0]==1]  #위의 과정을 한 큐에

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

### 전체 사용자 평점 평균 구하기 

In [45]:
# 전체 자료에서 평점 가져오기
ratings= data[:,2]
ratings
#평균 구하기
ratings.mean()    #파이썬 내장함수를 이용한 평균
print(np.mean(ratings))    #numpy 내장함수를 이용한 평균

3.581564453029317


### 1번 사용자의 평점 평균구하기

#### 1. id정보 가져오기
#### 2. id정보와 비교해서 boolean 데이터 만들기
#### 3. boolean 인덱싱 하기
#### 4. 인덱싱한 자료에서 평점만 가져오기
#### 5. 가져온 평점 평균 구하기

In [58]:
#!
user_id = data[:,0]
#2
user_id_bfilter=user_id==1
#3
user_1_data = data[user_id_bfilter]
print(user_1_data)
#4
user_1_rating = user_1_data[:,2]
#5
mean= np.mean(user_1_rating)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]
 [        1      2321         3 978302205]
 [        1       720         3 978300760]
 [        1      1270         5 978300055]
 [        1

In [59]:
mean

4.188679245283019

In [60]:
#위의 문제를 한 큐에 해결하기!!
data[data[:,0]==1,2].mean()

4.188679245283019